### ISSUE TITLE
If a config.json is present in the root folder the build failed

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/nd#1]
Apparently the script is too permissive.

Just create a config.json in root folder of project.

`touch config.json`

then run:

`npm run build`

It fails.

**Comment by hugohil** [comment]
Issue has been resolved, but IMO, and as recently specified in the doc, you **should not** write anywhere else than the following files and folders:

`src/`
`electron/`
`static/`
`test/`
`index.html` (careful with that one)

Also, `package.json` modifications are allowed when they come from an `npm install/update/uninstall [options]` command.

Therefore any other modification to the nd template leading to a misbehaviour cannot be considered as a "bug". In your case, I'm guessing you wanted to be able to pass custom options to your Electron main process and that lead you to create a `config.json` file at the project root, but this would actually be a new feature (that will come very soon for what it's worth).

So script is not really "too permissive", it just is for a feature that's not already there.

**Comment by gabrielstuff** [comment]
Not exactly. I was just using an other tool which generated the `conf.json` for me. So I keep thinking adding extra files should not trigger errors even if `config` files are automagically loaded.

In the case of magic load like in `meteor` then we should warn the user that this file is been used.
