### ISSUE TITLE
Settings in nd

### ISSUE THREAD

**Issue by 4quet** [soixantecircuits/nd#15]
Settings in nd should be handled using [nconf](https://github.com/indexzero/nconf) like in other Soixante circuits opensource projects.
By default `settings.json` should be loaded. If it does not exists, `settings.default.json` is loaded, this file must exists inside the repo.
A command-line `-- settings` option should be available to use a specific settings file.
Example: `--settings ./settings/my-settings.json`

**Comment by ybeaufort** [comment]
Done in https://github.com/soixantecircuits/nd/commit/7142f6f9dddcb43d6b99481deb035e5c49c991dc by adding standard-settings
