### ISSUE TITLE
The vue-masonry component can not be loaded

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/nd#20]
Regarding this plugin: https://github.com/shershen08/vue-masonry it looks like an issue with webpack version.
Now that webpack fully support V2 and recommand switch to V2 we should move to.

https://github.com/shershen08/vue-masonry/issues/7

**Comment by ybeaufort** [comment]
Similar to #21 
And solved in https://github.com/soixantecircuits/nd/commit/c5f579244cc08a203022afecc22592d5fc219481
